services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ankoji-com-durgesh-web:prod
    container_name: ankoji-com-durgesh-web
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
